name: Build Godot with ANGLE Support

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        choco install ninja
        choco install gn

    - name: Clone depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git C:\depot_tools
        echo "Adding depot_tools to PATH"
        $env:PATH += ";C:\depot_tools"

    - name: Clone ANGLE repository
      run: |
        git clone https://chromium.googlesource.com/angle/angle.git C:\angle
        cd C:\angle
        python C:\depot_tools\gclient.py config --name angle --unmanaged https://chromium.googlesource.com/angle/angle.git
        python C:\depot_tools\gclient.py sync

    - name: Generate Build Files with GN
      run: |
        cd C:\angle
        gn gen out/uwp --args='target_os="winuwp" target_cpu="x64" is_component_build=false is_debug=false'
      
    - name: Build ANGLE with Ninja
      run: |
        cd C:\angle
        ninja -C out/uwp
