name: Build ANGLE and Godot with GLES3 support

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python (required for ANGLE's gclient and build scripts)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install required Python dependencies (needed for gclient)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install httplib2

      # Clone depot_tools and set up environment
      - name: Clone depot_tools and set up environment
        run: |
         git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
         # Set the depot_tools path explicitly
         $env:DEPOT_TOOLS_WIN_TOOLCHAIN=0
         echo "Adding depot_tools to PATH"
         $env:PATH += ";$(pwd)\depot_tools"
         # Ensure depot_tools and gclient are available
         gclient --version
         echo "depot_tools and gclient are available"
    
      # Clone the ANGLE repository and set up build tools
      - name: Clone ANGLE repository and set up build tools
        run: |
          # Clone the ANGLE repository
          git clone https://chromium.googlesource.com/angle/angle.git
          cd angle
          # Run bootstrap to set up the environment
          python scripts/bootstrap.py
          # Sync dependencies using gclient
          gclient config --name angle --unmanaged https://chromium.googlesource.com/angle/angle.git
          gclient sync

      # Build ANGLE with the correct configuration
      - name: Build ANGLE
        run: |
          cd angle
          gn gen out/uwp --args='target_os="winuwp" target_cpu="x64" is_component_build=false is_debug=false'
          ninja -C out/uwp

      # Clone and build Godot with ANGLE GLES3 support
      - name: Build Godot with ANGLE GLES3 support
        run: |
          # Clone the Godot repository
          git clone --branch 3.5.3 https://github.com/godotengine/godot.git
          cd godot
          # Set up Godot build to use ANGLE
          scons platform=windows target=release use_egl=yes use_gles3=yes
          # Optionally, configure the export for UWP
          scons platform=uwp target=release

      # Upload the Godot build as an artifact
      - name: Upload Godot Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: godot-uwp-build
          path: godot/bin/godot.windows.tools.64.exe  # Adjust path if needed
