name: Build ANGLE and Godot with GLES3 support

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python (required for ANGLE's gclient and build scripts)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies for ANGLE (git, python libraries, etc.)
      - name: Install dependencies
        run: |
          # Install Git (if not already available in the runner)
          choco install git
          # Install Python libraries required by depot_tools
          python -m pip install httplib2
          # Clone depot_tools repository to the current directory
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          # Add depot_tools to the system PATH using PowerShell
          $env:PATH += ";$(pwd)\depot_tools"
          echo "Depot tools added to path"

      # Verify depot_tools and gclient are available
      - name: Check gclient availability
        run: |
          # Check if gclient is available
          where gclient

      # Clone ANGLE repository and set up build tools
      - name: Clone ANGLE repository and set up build tools
        run: |
          # Clone the ANGLE repository
          git clone https://chromium.googlesource.com/angle/angle.git
          cd angle
          # Run bootstrap script to set up the environment
          python scripts/bootstrap.py
          # Sync dependencies using gclient (after depot_tools is added to the PATH)
          gclient config --name angle --unmanaged https://chromium.googlesource.com/angle/angle.git
          gclient sync
          
      # Build ANGLE with the correct configuration
      - name: Build ANGLE
        run: |
          cd angle
          gn gen out/uwp --args='target_os="winuwp" target_cpu="x64" is_component_build=false is_debug=false'
          ninja -C out/uwp

      # Build Godot with ANGLE support for GLES3
      - name: Build Godot with ANGLE GLES3 support
        run: |
          # Clone the Godot repository
          git clone --branch 3.5.3 https://github.com/godotengine/godot.git
          cd godot
          # Set up Godot build to use ANGLE
          scons platform=windows target=release use_egl=yes use_gles3=yes
          # Optionally, configure the export for UWP
          scons platform=uwp target=release

      # Upload the Godot build as an artifact
      - name: Upload Godot Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: godot-uwp-build
          path: godot/bin/godot.windows.tools.64.exe  # Adjust path if needed
