name: Fix Appx

on:
  workflow_dispatch:

jobs:
  fix_appx:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install 7zip
      run: |
        choco install 7zip -y

    - name: Run fix.bat
      run: |
        cmd /c fix.bat

    - name: Upload my_game.appx artifact
      uses: actions/upload-artifact@v3
      with:
        name: my_game.appx
        path: ./my_game.appx
