name: Download and Repack Appx

on:
  push:
    branches:
      - uwp

jobs:
  download_and_repack:
    runs-on: windows-latest

    steps:
      - name: Download export.appx from Google Drive
        run: |
          curl -L -o export.appx "https://drive.google.com/uc?export=download&id=1ODdhUmh4KixddOP1QWGOHeZHAgjDYkL0"

      - name: Extract the appx
        shell: cmd
        run: |
          "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86\makeappx.exe" unpack /p "%CD%\export.appx" /d "%CD%\extractDir"

      - name: Repack the appx
        shell: cmd
        run: |
          "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86\makeappx.exe" pack /d "%CD%\extractDir" /p "%CD%\export_repacked.appx"

      - name: Upload repacked appx file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: export-appx
          path: export_repacked.appx
