name: Fix Appx

on:
  workflow_dispatch:

jobs:
  fix_appx:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install 7-Zip
      run: |
        choco install 7zip -y

    - name: Setup Visual Studio Environment
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat"
        
    - name: Run fix.bat
      run: |
        cd ${{ github.workspace }}  # Change to the workspace directory
        cmd /c fix.bat

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my_game.appx
        path: my_game.appx
